(module asl-mem/tasks
  :d "Unified task management facade composing store, dependency DAG, and session lease sub-modules."
  :x [TaskReceipt
      AnticipatedRisk
      TaskTolerance
      TaskRecord
      PostAction
      PostActionQueue
      make-task-receipt
      receipt-is-verified?
      format-receipt-asn
      make-holistic-task
      make-task
      make-gap-task
      make-cybernetic-task
      task-owns-file?
      task-owns-intersect?
      task-overlap-files
      task-overlap-blast-radius?
      task-dependencies-satisfied?
      task-parallel-eligible?
      task-is-ready?
      task-find-ready
      task-claim
      task-claim-session
      task-is-claimed-by?
      task-is-lease-expired?
      task-recover-session
      task-spawn-subtask
      task-start
      task-advance-step
      task-capture-handoff
      task-attach-receipt
      task-complete
      task-format-asn
      task-format-holistic-asn
      make-anticipated-risk
      make-task-tolerance
      task-is-within-leeway?
      task-has-escalation-trigger?
      format-anticipated-risk-asn
      format-task-tolerance-asn
      claim
      state
      settle
      make-post-action
      make-post-action-queue
      post-action-enqueue
      post-action-drain
      format-post-action-asn]
  :i [(tasks_store)
      (tasks_dag)
      (tasks_lease)])
